const DEVOUPS_URL = "https://devou.ps/api/v1/endpoints"
const DEVOUPS_GROUPS = {
    "authentication": [
        "kerberos-kdc-ticket-server",
        "ldap",
        "ldaps"
    ],
    "critical": [
        "console-bocal",
        "dns",
        "gitlab",
        "gitlab-registry",
        "intranet-cri",
        "ldap-cri",
        "s3",
        "vault"
    ],
    "internal-services": [
        "bookstack",
        "k8s-argocd",
        "k8s-ops-grafana",
        "k8s-ops-prometheus",
        "k8s-prod-1-prometheus",
        "mail"
    ],
    "others": [
        "blog",
        "documentation",
        "maas",
        "oidc-redirection"
    ],
    "pie-sm": [
        "bttrack",
        "django-pxe",
        "fleet-manager",
        "ipxe"
    ],
    "student-services": [
        "git",
        "git-forge",
        "moodle-(cours)",
        "moodle-(exams)",
        "moodle-(recrutement)",
        "news",
        "rocket-chat",
        "wiki-prog"
    ]
}
const DEVOUPS_GROUPS_CODE = [
    "authentication",
    "critical",
    "internal-services",
    "others",
    "pie-sm",
    "student-services"
]
const DEVOUPS_SERVICES_CODE = [
    "kerberos-kdc-ticket-server",
    "ldap",
    "ldaps",
    "console-bocal",
    "dns",
    "gitlab",
    "gitlab-registry",
    "intranet-cri",
    "ldap-cri",
    "s3",
    "vault",
    "bookstack",
    "k8s-argocd",
    "k8s-ops-grafana",
    "k8s-ops-prometheus",
    "k8s-prod-1-prometheus",
    "mail",
    "blog",
    "documentation",
    "https-redirection",
    "maas",
    "oidc-redirection",
    "bttrack",
    "django-pxe",
    "fleet-manager",
    "ipxe",
    "git",
    "git-forge",
    "moodle-(cours)",
    "moodle-(exams)",
    "moodle-(recrutement)",
    "news",
    "rocket-chat",
    "wiki-prog"
]
const DEVOUPS_SERVICES_NAME = [
    "Kerberos KDC Ticket Server",
    "LDAP",
    "LDAPS",
    "Console Bocal",
    "DNS",
    "Gitlab",
    "Gitlab Registry",
    "Intranet CRI",
    "LDAP CRI",
    "S3",
    "Vault",
    "Bookstack",
    "K8s ArgoCD",
    "K8s Ops Grafana",
    "K8s Ops Prometheus",
    "K8s Prod 1 Prometheus",
    "Mail",
    "Blog",
    "Documentation",
    "HTTPS Redirection",
    "MaaS",
    "OIDC Redirection",
    "Bttrack",
    "Django PXE",
    "Fleet Manager",
    "iPXE",
    "Git",
    "Git Forge",
    "Moodle (cours)",
    "Moodle (exams)",
    "Moodle (recrutement)",
    "News",
    "Rocket.Chat",
    "Wiki Prog"
]
const DEVOUPS_SERVICES_CODE_SHORTEN = [
    "ticket-server",
    "ldap",
    "ldaps",
    "console-bocal",
    "dns",
    "gitlab",
    "gitlab-registry",
    "intranet-cri",
    "ldap-cri",
    "s3",
    "vault",
    "bookstack",
    "k8s-argocd",
    "k8s-ops-grafana",
    "k8s-ops-prometheus",
    "k8s-prod-prometheus",
    "mail",
    "blog",
    "documentation",
    "https-redirection",
    "maas",
    "oidc-redirection",
    "bttrack",
    "django-pxe",
    "fleet-manager",
    "ipxe",
    "git",
    "git-forge",
    "moodle-cours",
    "moodle-exams",
    "moodle-recrutement",
    "news",
    "rocket-chat",
    "wiki-prog"
]
module.exports = { DEVOUPS_GROUPS, DEVOUPS_GROUPS_CODE, DEVOUPS_SERVICES_CODE, DEVOUPS_SERVICES_CODE_SHORTEN, DEVOUPS_SERVICES_NAME, DEVOUPS_URL }